# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(511, 593)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 60, 251, 71))
        self.label.setStyleSheet("color: rgb(0, 85, 0);\n"
"\n"
"font: italic 14pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 231, 41))
        self.label_2.setStyleSheet("COLOR: rgb(85, 0, 0);\n"
"font: 14pt \"Yu Gothic\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 231, 41))
        self.label_3.setStyleSheet("COLOR: rgb(85, 0, 0);\n"
"font: 14pt \"Yu Gothic\";")
        self.label_3.setObjectName("label_3")
        self.firstname = QtWidgets.QLineEdit(Form)
        self.firstname.setGeometry(QtCore.QRect(270, 150, 141, 21))
        self.firstname.setStyleSheet("COLOR: rgb(0, 255, 0);\n"
"font: 75 15pt \"MS Sans Serif\";")
        self.firstname.setText("")
        self.firstname.setObjectName("firstname")
        self.lastname = QtWidgets.QLineEdit(Form)
        self.lastname.setGeometry(QtCore.QRect(270, 190, 141, 21))
        self.lastname.setStyleSheet("COLOR: rgb(0, 255, 0);\n"
"font: 75 15pt \"MS Sans Serif\";")
        self.lastname.setText("")
        self.lastname.setObjectName("lastname")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(190, 240, 121, 51))
        self.add.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"background: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69))")
        self.add.setObjectName("add")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 350, 141, 31))
        self.label_4.setStyleSheet("COLOR: rgb(170, 0, 0);\n"
"font: 75 20pt \"Century Schoolbook\";")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Adding the first and last name"))
        self.label_2.setText(_translate("Form", "ENTER THE FIRST NAME:"))
        self.label_3.setText(_translate("Form", "ENTER THE LAST NAME:"))
        self.add.setText(_translate("Form", "ADD"))
        self.label_4.setText(_translate("Form", "RESULT:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
