# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calci.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 618)
        self.heading = QtWidgets.QLabel(Form)
        self.heading.setGeometry(QtCore.QRect(100, 80, 331, 41))
        self.heading.setStyleSheet("COLOR: rgb(255, 0, 0);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.heading.setObjectName("heading")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 170, 161, 31))
        self.label_2.setStyleSheet("font: 11pt \"MS PGothic\";\n"
"COLOR: rgb(85, 0, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 230, 171, 21))
        self.label_3.setStyleSheet("font: 11pt \"MS PGothic\";\n"
"COLOR: rgb(85, 0, 255)")
        self.label_3.setObjectName("label_3")
        self.box1 = QtWidgets.QLineEdit(Form)
        self.box1.setGeometry(QtCore.QRect(270, 180, 113, 20))
        self.box1.setObjectName("box1")
        self.box2 = QtWidgets.QLineEdit(Form)
        self.box2.setGeometry(QtCore.QRect(270, 230, 113, 20))
        self.box2.setObjectName("box2")
        self.result = QtWidgets.QLabel(Form)
        self.result.setGeometry(QtCore.QRect(40, 480, 131, 51))
        self.result.setStyleSheet("font: 11pt \"MS PGothic\";\n"
"font: 50 25pt \"MS Shell Dlg 2\";\n"
"COLOR: rgb(85, 0, 255)")
        self.result.setObjectName("result")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(60, 290, 75, 71))
        self.add.setStyleSheet("color: rgb(255, 255, 0);\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.add.setObjectName("add")
        self.sub = QtWidgets.QPushButton(Form)
        self.sub.setGeometry(QtCore.QRect(170, 290, 75, 71))
        self.sub.setStyleSheet("color: rgb(255, 255, 0);\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.sub.setObjectName("sub")
        self.multi = QtWidgets.QPushButton(Form)
        self.multi.setGeometry(QtCore.QRect(280, 290, 75, 71))
        self.multi.setStyleSheet("color: rgb(255, 255, 0);\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.multi.setObjectName("multi")
        self.div = QtWidgets.QPushButton(Form)
        self.div.setGeometry(QtCore.QRect(390, 290, 75, 71))
        self.div.setStyleSheet("color: rgb(255, 255, 0);\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.div.setObjectName("div")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(180, 390, 191, 71))
        self.pushButton.setStyleSheet("background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 2, 6)")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.heading.setText(_translate("Form", "SIMPLE CALCULATOR"))
        self.label_2.setText(_translate("Form", "ENTER FIRST NUMBER:"))
        self.label_3.setText(_translate("Form", "ENTER SECOND NUMBER:"))
        self.result.setText(_translate("Form", "RESULT:"))
        self.add.setText(_translate("Form", "+"))
        self.sub.setText(_translate("Form", "-"))
        self.multi.setText(_translate("Form", "*"))
        self.div.setText(_translate("Form", "/"))
        self.pushButton.setText(_translate("Form", "CALCULATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
